# Generated by Django 3.0.8 on 2020-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_post_id', models.CharField(max_length=7, unique=True)),
                ('obs_post_name', models.CharField(max_length=20)),
                ('obs_lat', models.DecimalField(decimal_places=15, max_digits=999)),
                ('obs_lon', models.DecimalField(decimal_places=15, max_digits=999)),
                ('obs_object', models.CharField(max_length=30)),
                ('data_type', models.CharField(max_length=10)),
            ],
        ),
    ]
