# Generated by Django 3.0.6 on 2020-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationpost',
            name='id',
        ),
        migrations.AlterField(
            model_name='observationpost',
            name='obs_post_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
