# Generated by Django 3.0.6 on 2020-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
