# Generated by Django 3.0.6 on 2020-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200803_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, upload_to='license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
