# Generated by Django 3.0.6 on 2020-08-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200803_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='license_photo',
            new_name='license_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
