# Generated by Django 3.0.6 on 2020-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200803_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_image',
            field=models.ImageField(default='license/default.JPG', upload_to='license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile/default.JPG', upload_to='profile'),
        ),
    ]
