# Generated by Django 3.0.6 on 2020-06-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_buddy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddy',
            old_name='user',
            new_name='diver',
        ),
    ]
