# Generated by Django 3.0.6 on 2020-06-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200610_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buddy',
        ),
    ]
