# Generated by Django 3.0.6 on 2020-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_buddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='license_photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
