# Generated by Django 3.0.6 on 2020-06-22 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivePoint',
            fields=[
                ('point_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('point_nm', models.CharField(max_length=20, unique=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=999)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=999)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiveLog',
            fields=[
                ('log_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('log_nm', models.CharField(max_length=20, unique=True)),
                ('dive_date', models.DateTimeField()),
                ('dive_time', models.TimeField()),
                ('temperature', models.SmallIntegerField()),
                ('max_depth', models.SmallIntegerField()),
                ('buddy', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dive.DivePoint')),
            ],
        ),
    ]
