# Generated by Django 3.0.8 on 2020-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divelog',
            name='log_id',
        ),
        migrations.RemoveField(
            model_name='divepoint',
            name='point_id',
        ),
    ]
