# Generated by Django 3.0.8 on 2020-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0002_auto_20200707_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelog',
            name='log_nm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='divepoint',
            name='point_nm',
            field=models.CharField(max_length=20),
        ),
    ]
