# Generated by Django 3.0.6 on 2020-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0005_auto_20200708_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelog',
            name='buddy',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='dive_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='dive_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='max_depth',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='temperature',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='divepoint',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
