# Generated by Django 3.0.6 on 2020-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0006_auto_20200717_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelog',
            name='dive_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='max_depth',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='temperature',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
