# Generated by Django 3.0.6 on 2020-08-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0008_divecertorgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiveCertOrgs',
            new_name='DiveCertOrg',
        ),
    ]
