# Generated by Django 3.0.6 on 2020-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0009_auto_20200805_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='divecertorg',
            name='org_step',
            field=models.SmallIntegerField(default=0),
        ),
    ]
