# Generated by Django 3.0.6 on 2020-08-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0010_divecertorg_org_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divecertorg',
            old_name='org_level',
            new_name='cert_level',
        ),
        migrations.RenameField(
            model_name='divecertorg',
            old_name='org_step',
            new_name='cert_step',
        ),
    ]
