# Generated by Django 3.0.6 on 2020-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivePoint',
            fields=[
                ('point_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('point_nm', models.CharField(max_length=100, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=999)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=999)),
                ('address', models.CharField(max_length=20)),
                ('diver_id', models.CharField(max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
