# Generated by Django 3.0.6 on 2020-06-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DivePoint',
        ),
    ]
